openapi: 3.0.0
info:
  title: data types for person identifiers
  version: ${project.version}
servers: []
paths: {}
components:
  parameters:
    SsinPathParameter:
      description: Social Security Identification Number issued by the National Register or CBSS
      in: path
      name: ssin
      required: true
      schema:
        "$ref": "#/components/schemas/Ssin"
    SsinQueryParameter:
      description: Social Security Identification Number issued by the National Register or CBSS
      in: query
      name: ssin
      schema:
        "$ref": "#/components/schemas/Ssin"
  schemas:
    Ssin:
      description: Social Security Identification Number issued by the National Register or CBSS
      type: string
      pattern: '^\d{11}$'
      example: "00000000196"
